//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはReEngineのGUIツールによって生成されました。
//     このファイルへの変更は、不正な動作の原因になったり、
//     コードが再生成されるときに損失したりしますので編集しないでください。
// </auto-generated>
//------------------------------------------------------------------------------

// [Settings]
// ExportUnusedSymbol = False
// ReferenceExternalSymbol = False
// UseGUIStringPath = False

namespace via.gui.asset
{
	public class ChoiceControllerUI
	{
		// Root objects
		
		public static _Root_ Root { get { return new _Root_(1219645687); } }
		
		public static _PNL_Bg_ PNL_Bg { get { return new _PNL_Bg_(2350338275); } }
		
		public static _PNL_Choice_ PNL_Choice { get { return new _PNL_Choice_(3222721482); } }
		
		public static _PNL_Player_ PNL_Player { get { return new _PNL_Player_(1093712210); } }
		
		// Symbol define
		public static class SymbolDef
		{
			/// <summary>[Type=via.gui.View]</summary>
			public static _Root_ Root { get { return new _Root_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_1_ PNL_1 { get { return new _PNL_1_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_1P_ PNL_1P { get { return new _PNL_1P_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_1player_ PNL_1player { get { return new _PNL_1player_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_2P_ PNL_2P { get { return new _PNL_2P_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Bg_ PNL_Bg { get { return new _PNL_Bg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Choice_ PNL_Choice { get { return new _PNL_Choice_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Player_ PNL_Player { get { return new _PNL_Player_(); } }
		}
		
		// Symbols
		
		/// <summary>Root [Type=via.gui.View]</summary>
		public class _Root_ : via.gui.GUIHashPath<via.gui.View>
		{
			
			public _Root_() : base(){}
			public _Root_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Bg_ PNL_Bg { get { if (_0 == null) { create(ref _0, 2350338275); } return _0; } }
			public _PNL_Choice_ PNL_Choice { get { if (_1 == null) { create(ref _1, 3222721482); } return _1; } }
			public _PNL_Player_ PNL_Player { get { if (_2 == null) { create(ref _2, 1093712210); } return _2; } }
			
			public class _ParamVarDefine_
			{
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2p_selected_Visible { get { return new GUIParamVarDefine<bool>(2638245260); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2p_Visible { get { return new GUIParamVarDefine<bool>(3728053200); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1p_selected_Visible { get { return new GUIParamVarDefine<bool>(1592913395); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1p_Visible { get { return new GUIParamVarDefine<bool>(1107485401); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_1P_PlayState { get { return new GUIParamVarDefine<string>(1789291670); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_2P_PlayState { get { return new GUIParamVarDefine<string>(1332588785); } }
			}
			public _ParamVarDefine_ ParamDef { get { if (_p == null) { _p = new _ParamVarDefine_(); } return _p; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>無効</summary>
			public string State_DISABLE { get { return _State_DISABLE; } } 
			/// <summary>IN演出</summary>
			public string State_FADE_IN { get { return _State_FADE_IN; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private _PNL_Bg_ _0;
			private _PNL_Choice_ _1;
			private _PNL_Player_ _2;
			private _ParamVarDefine_ _p;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_DISABLE = "DISABLE";
			private const string _State_FADE_IN = "FADE_IN";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_1 [Type=via.gui.Panel]</summary>
		public class _PNL_1_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_1_() : base(){}
			public _PNL_1_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_2p { get { if (_0 == null) { create(ref _0, 4172917353); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_2p_selected { get { if (_1 == null) { create(ref _1, 1113932608); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_Selected { get { return _State_Selected; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_Selected = "Selected";
			#endregion
		}
		
		/// <summary>PNL_1P [Type=via.gui.Panel]</summary>
		public class _PNL_1P_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_1P_() : base(){}
			public _PNL_1P_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_1player_ PNL_1player { get { if (_0 == null) { create(ref _0, 3521796327); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_GoPink_1P { get { return _State_GoPink_1P; } } 
			public string State_StayPink_1P { get { return _State_StayPink_1P; } } 
			public string State_StayPink_Selected_Start_1P { get { return _State_StayPink_Selected_Start_1P; } } 
			public string State_StayPink_Selected_1P { get { return _State_StayPink_Selected_1P; } } 
			public string State_GoBlue_1P { get { return _State_GoBlue_1P; } } 
			public string State_StayBlue_1P { get { return _State_StayBlue_1P; } } 
			public string State_StayBlue_Selected_Start_1P { get { return _State_StayBlue_Selected_Start_1P; } } 
			public string State_StayBlue_Selected_1P { get { return _State_StayBlue_Selected_1P; } } 
			
			#region field (internal)
			private _PNL_1player_ _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_GoPink_1P = "GoPink_1P";
			private const string _State_StayPink_1P = "StayPink_1P";
			private const string _State_StayPink_Selected_Start_1P = "StayPink_Selected_Start_1P";
			private const string _State_StayPink_Selected_1P = "StayPink_Selected_1P";
			private const string _State_GoBlue_1P = "GoBlue_1P";
			private const string _State_StayBlue_1P = "StayBlue_1P";
			private const string _State_StayBlue_Selected_Start_1P = "StayBlue_Selected_Start_1P";
			private const string _State_StayBlue_Selected_1P = "StayBlue_Selected_1P";
			#endregion
		}
		
		/// <summary>PNL_1player [Type=via.gui.Panel]</summary>
		public class _PNL_1player_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_1player_() : base(){}
			public _PNL_1player_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_1p { get { if (_0 == null) { create(ref _0, 510977827); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_1p_selected { get { if (_1 == null) { create(ref _1, 1957005576); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_Selected { get { return _State_Selected; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_Selected = "Selected";
			#endregion
		}
		
		/// <summary>PNL_2P [Type=via.gui.Panel]</summary>
		public class _PNL_2P_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_2P_() : base(){}
			public _PNL_2P_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_1_ PNL_2player { get { if (_0 == null) { create(ref _0, 797218636); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_GoPink_2P { get { return _State_GoPink_2P; } } 
			public string State_StayPink_2P { get { return _State_StayPink_2P; } } 
			public string State_StayPink_Selected_Start_2P { get { return _State_StayPink_Selected_Start_2P; } } 
			public string State_StayPink_Selected_2P { get { return _State_StayPink_Selected_2P; } } 
			public string State_GoBlue_2P { get { return _State_GoBlue_2P; } } 
			public string State_StayBlue_2P { get { return _State_StayBlue_2P; } } 
			public string State_StayBlue_Selected_Start_2P { get { return _State_StayBlue_Selected_Start_2P; } } 
			public string State_StayBlue_Selected_2P { get { return _State_StayBlue_Selected_2P; } } 
			
			#region field (internal)
			private _PNL_1_ _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_GoPink_2P = "GoPink_2P";
			private const string _State_StayPink_2P = "StayPink_2P";
			private const string _State_StayPink_Selected_Start_2P = "StayPink_Selected_Start_2P";
			private const string _State_StayPink_Selected_2P = "StayPink_Selected_2P";
			private const string _State_GoBlue_2P = "GoBlue_2P";
			private const string _State_StayBlue_2P = "StayBlue_2P";
			private const string _State_StayBlue_Selected_Start_2P = "StayBlue_Selected_Start_2P";
			private const string _State_StayBlue_Selected_2P = "StayBlue_Selected_2P";
			#endregion
		}
		
		/// <summary>PNL_Bg [Type=via.gui.Panel]</summary>
		public class _PNL_Bg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Bg_() : base(){}
			public _PNL_Bg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_bg { get { if (_0 == null) { create(ref _0, 3611605884); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Choice [Type=via.gui.Panel]</summary>
		public class _PNL_Choice_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Choice_() : base(){}
			public _PNL_Choice_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_select { get { if (_0 == null) { create(ref _0, 2761577270); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Player [Type=via.gui.Panel]</summary>
		public class _PNL_Player_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Player_() : base(){}
			public _PNL_Player_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_1P_ PNL_1P { get { if (_0 == null) { create(ref _0, 87706410); } return _0; } }
			public _PNL_2P_ PNL_2P { get { if (_1 == null) { create(ref _1, 3381837793); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_1P_ _0;
			private _PNL_2P_ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		#region Legacy GUI Parameter Variable IDs (GPI)
		
		// ※ 旧仕様向けの出力です。Rootや各コントロールのParamDefクラス以下に変数定義があるのでそちらを利用してください。
		
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1p_selected_Visibleに書き換えてください。")]
		public static string GPI_tex_1p_selected_Visible = "tex_1p_selected_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1p_Visibleに書き換えてください。")]
		public static string GPI_tex_1p_Visible = "tex_1p_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2p_selected_Visibleに書き換えてください。")]
		public static string GPI_tex_2p_selected_Visible = "tex_2p_selected_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2p_Visibleに書き換えてください。")]
		public static string GPI_tex_2p_Visible = "tex_2p_Visible";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_1P_PlayStateに書き換えてください。")]
		public static string GPI_PNL_1P_PlayState = "PNL_1P_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_2P_PlayStateに書き換えてください。")]
		public static string GPI_PNL_2P_PlayState = "PNL_2P_PlayState";
		
		#endregion
		
	}
}

