//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはReEngineのGUIツールによって生成されました。
//     このファイルへの変更は、不正な動作の原因になったり、
//     コードが再生成されるときに損失したりしますので編集しないでください。
// </auto-generated>
//------------------------------------------------------------------------------

// [Settings]
// ExportUnusedSymbol = False
// ReferenceExternalSymbol = False
// UseGUIStringPath = False

namespace via.gui.asset
{
	public class InGameGUI
	{
		// Root objects
		
		public static _Root_ Root { get { return new _Root_(1219645687); } }
		
		public static _PNL_Terop_ PNL_Terop { get { return new _PNL_Terop_(1534051143); } }
		
		public static _PNL_InGame_ PNL_InGame { get { return new _PNL_InGame_(122002293); } }
		
		public static _PNL_UnderBg_ PNL_UnderBg { get { return new _PNL_UnderBg_(3467830877); } }
		
		// Symbol define
		public static class SymbolDef
		{
			/// <summary>[Type=via.gui.View]</summary>
			public static _Root_ Root { get { return new _Root_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL__ PNL_ { get { return new _PNL__(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_1st_ PNL_1st { get { return new _PNL_1st_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_2st_ PNL_2st { get { return new _PNL_2st_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Aari_ PNL_Aari { get { return new _PNL_Aari_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_B_GaugeBg_ PNL_B_GaugeBg { get { return new _PNL_B_GaugeBg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_B_HPbg_ PNL_B_HPbg { get { return new _PNL_B_HPbg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_B_MPbg_ PNL_B_MPbg { get { return new _PNL_B_MPbg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Blue_HP_ PNL_Blue_HP { get { return new _PNL_Blue_HP_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Blue_MP_ PNL_Blue_MP { get { return new _PNL_Blue_MP_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_BlueBeam_ PNL_BlueBeam { get { return new _PNL_BlueBeam_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_BlueBg_ PNL_BlueBg { get { return new _PNL_BlueBg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_BlueGauge_ PNL_BlueGauge { get { return new _PNL_BlueGauge_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_BlueIcon_ PNL_BlueIcon { get { return new _PNL_BlueIcon_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_BlueLariat_ PNL_BlueLariat { get { return new _PNL_BlueLariat_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_BlueTeam_ PNL_BlueTeam { get { return new _PNL_BlueTeam_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Egi_ PNL_Egi { get { return new _PNL_Egi_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_InGame_ PNL_InGame { get { return new _PNL_InGame_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_MoveHP_Aari_ PNL_MoveHP_Aari { get { return new _PNL_MoveHP_Aari_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_MoveHP_BG_Aari_ PNL_MoveHP_BG_Aari { get { return new _PNL_MoveHP_BG_Aari_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_MoveHP_BG_Egi_ PNL_MoveHP_BG_Egi { get { return new _PNL_MoveHP_BG_Egi_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_MoveHP_Egi_ PNL_MoveHP_Egi { get { return new _PNL_MoveHP_Egi_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_MoveLife_ PNL_MoveLife { get { return new _PNL_MoveLife_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Num_ PNL_Num { get { return new _PNL_Num_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_P_GaugeBg_ PNL_P_GaugeBg { get { return new _PNL_P_GaugeBg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_P_HPbg_ PNL_P_HPbg { get { return new _PNL_P_HPbg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_P_MPbg_ PNL_P_MPbg { get { return new _PNL_P_MPbg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Pink_HP_ PNL_Pink_HP { get { return new _PNL_Pink_HP_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Pink_MP_ PNL_Pink_MP { get { return new _PNL_Pink_MP_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_PinkBeam_ PNL_PinkBeam { get { return new _PNL_PinkBeam_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_PinkBg_ PNL_PinkBg { get { return new _PNL_PinkBg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_PinkGauge_ PNL_PinkGauge { get { return new _PNL_PinkGauge_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_PinkIcon_ PNL_PinkIcon { get { return new _PNL_PinkIcon_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_PinkLariat_ PNL_PinkLariat { get { return new _PNL_PinkLariat_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_PinkTeam_ PNL_PinkTeam { get { return new _PNL_PinkTeam_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Terop_ PNL_Terop { get { return new _PNL_Terop_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_TimeLimit_ PNL_TimeLimit { get { return new _PNL_TimeLimit_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_UnderBg_ PNL_UnderBg { get { return new _PNL_UnderBg_(); } }
		}
		
		// Symbols
		
		/// <summary>Root [Type=via.gui.View]</summary>
		public class _Root_ : via.gui.GUIHashPath<via.gui.View>
		{
			
			public _Root_() : base(){}
			public _Root_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Terop_ PNL_Terop { get { if (_1 == null) { create(ref _1, 1534051143); } return _1; } }
			public _PNL_InGame_ PNL_InGame { get { if (_2 == null) { create(ref _2, 122002293); } return _2; } }
			public _PNL_UnderBg_ PNL_UnderBg { get { if (_3 == null) { create(ref _3, 3467830877); } return _3; } }
			
			public class _ParamVarDefine_
			{
				/// <summary>[Type Float2] </summary>
				public GUIParamVarDefine<via.Float2> tex_Bar_B_Size { get { return new GUIParamVarDefine<via.Float2>(3939769030); } }
				
				/// <summary>[Type Integer] </summary>
				public GUIParamVarDefine<int> tex_Bar_B_RectW { get { return new GUIParamVarDefine<int>(568467340); } }
				
				/// <summary>[Type Float2] </summary>
				public GUIParamVarDefine<via.Float2> tex_Bar_P_Size { get { return new GUIParamVarDefine<via.Float2>(742372916); } }
				
				/// <summary>[Type Integer] </summary>
				public GUIParamVarDefine<int> tex_Bar_P_RectW { get { return new GUIParamVarDefine<int>(1746889748); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_0_Visible { get { return new GUIParamVarDefine<bool>(158423174); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_1_Visible { get { return new GUIParamVarDefine<bool>(1350130747); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_2_Visible { get { return new GUIParamVarDefine<bool>(3139461295); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_3_Visible { get { return new GUIParamVarDefine<bool>(4133533458); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_4_Visible { get { return new GUIParamVarDefine<bool>(2399222301); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_5_Visible { get { return new GUIParamVarDefine<bool>(429601543); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_6_Visible { get { return new GUIParamVarDefine<bool>(598502784); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_7_Visible { get { return new GUIParamVarDefine<bool>(3125460697); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_8_Visible { get { return new GUIParamVarDefine<bool>(2349624524); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_9_Visible { get { return new GUIParamVarDefine<bool>(251640015); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_2_Visible { get { return new GUIParamVarDefine<bool>(1355239676); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_3_Visible { get { return new GUIParamVarDefine<bool>(3289315109); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_4_Visible { get { return new GUIParamVarDefine<bool>(3174662094); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_5_Visible { get { return new GUIParamVarDefine<bool>(3778517565); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_6_Visible { get { return new GUIParamVarDefine<bool>(2439526607); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_7_Visible { get { return new GUIParamVarDefine<bool>(1643974157); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_8_Visible { get { return new GUIParamVarDefine<bool>(590842866); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_9_Visible { get { return new GUIParamVarDefine<bool>(2196750390); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Terop_PlayState { get { return new GUIParamVarDefine<string>(1299461484); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_1_Visible { get { return new GUIParamVarDefine<bool>(1959472007); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_0_Visible { get { return new GUIParamVarDefine<bool>(1853667042); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Seena_Beam_PlayState { get { return new GUIParamVarDefine<string>(2334015641); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Frula_Beam_PlayState { get { return new GUIParamVarDefine<string>(428062716); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Aari_HP_PlayState { get { return new GUIParamVarDefine<string>(1917894176); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Frula_MP_PlayState { get { return new GUIParamVarDefine<string>(2133339576); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Egi_HP_PlayState { get { return new GUIParamVarDefine<string>(2250647105); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Sheena_MP_PlayState { get { return new GUIParamVarDefine<string>(3599025263); } }
				
				/// <summary>[Type Float3] </summary>
				public GUIParamVarDefine<via.Float3> PNL_Egi_Position { get { return new GUIParamVarDefine<via.Float3>(606550724); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Egi_Visible { get { return new GUIParamVarDefine<bool>(3331904802); } }
				
				/// <summary>[Type Float3] </summary>
				public GUIParamVarDefine<via.Float3> PNL_Aari_Position { get { return new GUIParamVarDefine<via.Float3>(1325635977); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Aari_Visible { get { return new GUIParamVarDefine<bool>(1972078408); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_MoveHP_Egi_PlayState { get { return new GUIParamVarDefine<string>(251211941); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_MoveHP_Aari_PlayState { get { return new GUIParamVarDefine<string>(3711434560); } }
			}
			public _ParamVarDefine_ ParamDef { get { if (_p == null) { _p = new _ParamVarDefine_(); } return _p; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>無効</summary>
			public string State_DISABLE { get { return _State_DISABLE; } } 
			/// <summary>IN演出</summary>
			public string State_FADE_IN { get { return _State_FADE_IN; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private _PNL_Terop_ _1;
			private _PNL_InGame_ _2;
			private _PNL_UnderBg_ _3;
			private _ParamVarDefine_ _p;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_DISABLE = "DISABLE";
			private const string _State_FADE_IN = "FADE_IN";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_ [Type=via.gui.Panel]</summary>
		public class _PNL__ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL__() : base(){}
			public _PNL__(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_limit { get { if (_0 == null) { create(ref _0, 1658911404); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_1st [Type=via.gui.Panel]</summary>
		public class _PNL_1st_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_1st_() : base(){}
			public _PNL_1st_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_0 { get { if (_0 == null) { create(ref _0, 1777110518); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_1 { get { if (_1 == null) { create(ref _1, 919952205); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_2 { get { if (_2 == null) { create(ref _2, 2799471434); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_3 { get { if (_3 == null) { create(ref _3, 2858414422); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_4 { get { if (_4 == null) { create(ref _4, 874142103); } return _4; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_5 { get { if (_5 == null) { create(ref _5, 2545007004); } return _5; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_6 { get { if (_6 == null) { create(ref _6, 1405700660); } return _6; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_7 { get { if (_7 == null) { create(ref _7, 3868133323); } return _7; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_8 { get { if (_8 == null) { create(ref _8, 1921129301); } return _8; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_9 { get { if (_9 == null) { create(ref _9, 286926054); } return _9; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private via.gui.GUIHashPath<via.gui.Texture> _5;
			private via.gui.GUIHashPath<via.gui.Texture> _6;
			private via.gui.GUIHashPath<via.gui.Texture> _7;
			private via.gui.GUIHashPath<via.gui.Texture> _8;
			private via.gui.GUIHashPath<via.gui.Texture> _9;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_2st [Type=via.gui.Panel]</summary>
		public class _PNL_2st_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_2st_() : base(){}
			public _PNL_2st_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_0 { get { if (_0 == null) { create(ref _0, 1777110518); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_1 { get { if (_1 == null) { create(ref _1, 919952205); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_2 { get { if (_2 == null) { create(ref _2, 2799471434); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_3 { get { if (_3 == null) { create(ref _3, 2858414422); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_4 { get { if (_4 == null) { create(ref _4, 874142103); } return _4; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_5 { get { if (_5 == null) { create(ref _5, 2545007004); } return _5; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_6 { get { if (_6 == null) { create(ref _6, 1405700660); } return _6; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_7 { get { if (_7 == null) { create(ref _7, 3868133323); } return _7; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_8 { get { if (_8 == null) { create(ref _8, 1921129301); } return _8; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_9 { get { if (_9 == null) { create(ref _9, 286926054); } return _9; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private via.gui.GUIHashPath<via.gui.Texture> _5;
			private via.gui.GUIHashPath<via.gui.Texture> _6;
			private via.gui.GUIHashPath<via.gui.Texture> _7;
			private via.gui.GUIHashPath<via.gui.Texture> _8;
			private via.gui.GUIHashPath<via.gui.Texture> _9;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Aari [Type=via.gui.Panel]</summary>
		public class _PNL_Aari_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Aari_() : base(){}
			public _PNL_Aari_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_MoveHP_Aari_ PNL_MoveHP_Aari { get { if (_0 == null) { create(ref _0, 2544221633); } return _0; } }
			public _PNL_MoveHP_BG_Aari_ PNL_MoveHP_BG_Aari { get { if (_1 == null) { create(ref _1, 3705167085); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_MoveHP_Aari_ _0;
			private _PNL_MoveHP_BG_Aari_ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_B_GaugeBg [Type=via.gui.Panel]</summary>
		public class _PNL_B_GaugeBg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_B_GaugeBg_() : base(){}
			public _PNL_B_GaugeBg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_B_bg { get { if (_0 == null) { create(ref _0, 1996911567); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_B_HPbg [Type=via.gui.Panel]</summary>
		public class _PNL_B_HPbg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_B_HPbg_() : base(){}
			public _PNL_B_HPbg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP1 { get { if (_0 == null) { create(ref _0, 2368806892); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP2 { get { if (_1 == null) { create(ref _1, 4108067642); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP3 { get { if (_2 == null) { create(ref _2, 3803888176); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP4 { get { if (_3 == null) { create(ref _3, 3229955701); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP5 { get { if (_4 == null) { create(ref _4, 810787143); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_B_MPbg [Type=via.gui.Panel]</summary>
		public class _PNL_B_MPbg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_B_MPbg_() : base(){}
			public _PNL_B_MPbg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP1 { get { if (_0 == null) { create(ref _0, 488565980); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP2 { get { if (_1 == null) { create(ref _1, 1667977655); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP3 { get { if (_2 == null) { create(ref _2, 2096175435); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP4 { get { if (_3 == null) { create(ref _3, 1763211850); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP5 { get { if (_4 == null) { create(ref _4, 962091416); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Blue_HP [Type=via.gui.Panel]</summary>
		public class _PNL_Blue_HP_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Blue_HP_() : base(){}
			public _PNL_Blue_HP_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP1 { get { if (_0 == null) { create(ref _0, 2368806892); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP2 { get { if (_1 == null) { create(ref _1, 4108067642); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP3 { get { if (_2 == null) { create(ref _2, 3803888176); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP4 { get { if (_3 == null) { create(ref _3, 3229955701); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP5 { get { if (_4 == null) { create(ref _4, 810787143); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Life5 { get { return _State_Life5; } } 
			public string State_Life4 { get { return _State_Life4; } } 
			public string State_Life3 { get { return _State_Life3; } } 
			public string State_Life2 { get { return _State_Life2; } } 
			public string State_Life1 { get { return _State_Life1; } } 
			public string State_Life0 { get { return _State_Life0; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_Life5 = "Life5";
			private const string _State_Life4 = "Life4";
			private const string _State_Life3 = "Life3";
			private const string _State_Life2 = "Life2";
			private const string _State_Life1 = "Life1";
			private const string _State_Life0 = "Life0";
			#endregion
		}
		
		/// <summary>PNL_Blue_MP [Type=via.gui.Panel]</summary>
		public class _PNL_Blue_MP_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Blue_MP_() : base(){}
			public _PNL_Blue_MP_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP1 { get { if (_0 == null) { create(ref _0, 488565980); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP2 { get { if (_1 == null) { create(ref _1, 1667977655); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP3 { get { if (_2 == null) { create(ref _2, 2096175435); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP4 { get { if (_3 == null) { create(ref _3, 1763211850); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP5 { get { if (_4 == null) { create(ref _4, 962091416); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_MP5 { get { return _State_MP5; } } 
			public string State_MP4 { get { return _State_MP4; } } 
			public string State_MP3 { get { return _State_MP3; } } 
			public string State_MP2 { get { return _State_MP2; } } 
			public string State_MP1 { get { return _State_MP1; } } 
			public string State_MP0 { get { return _State_MP0; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_MP5 = "MP5";
			private const string _State_MP4 = "MP4";
			private const string _State_MP3 = "MP3";
			private const string _State_MP2 = "MP2";
			private const string _State_MP1 = "MP1";
			private const string _State_MP0 = "MP0";
			#endregion
		}
		
		/// <summary>PNL_BlueBeam [Type=via.gui.Panel]</summary>
		public class _PNL_BlueBeam_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_BlueBeam_() : base(){}
			public _PNL_BlueBeam_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_Bwitch { get { if (_0 == null) { create(ref _0, 3269327807); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_Bwitch_bg { get { if (_1 == null) { create(ref _1, 3371721027); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_charge { get { return _State_charge; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_charge = "charge";
			#endregion
		}
		
		/// <summary>PNL_BlueBg [Type=via.gui.Panel]</summary>
		public class _PNL_BlueBg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_BlueBg_() : base(){}
			public _PNL_BlueBg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_B_HPbg_ PNL_B_HPbg { get { if (_0 == null) { create(ref _0, 2173925733); } return _0; } }
			public _PNL_B_MPbg_ PNL_B_MPbg { get { if (_1 == null) { create(ref _1, 3840498066); } return _1; } }
			public _PNL_B_GaugeBg_ PNL_B_GaugeBg { get { if (_2 == null) { create(ref _2, 3265688505); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_IconMPbg { get { if (_3 == null) { create(ref _3, 1226735192); } return _3; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_B_HPbg_ _0;
			private _PNL_B_MPbg_ _1;
			private _PNL_B_GaugeBg_ _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_BlueGauge [Type=via.gui.Panel]</summary>
		public class _PNL_BlueGauge_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_BlueGauge_() : base(){}
			public _PNL_BlueGauge_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_B { get { if (_0 == null) { create(ref _0, 3105613049); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_BlueIcon [Type=via.gui.Panel]</summary>
		public class _PNL_BlueIcon_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_BlueIcon_() : base(){}
			public _PNL_BlueIcon_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Icon_Egi { get { if (_0 == null) { create(ref _0, 174641956); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_BlueLariat [Type=via.gui.Panel]</summary>
		public class _PNL_BlueLariat_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_BlueLariat_() : base(){}
			public _PNL_BlueLariat_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_lariat { get { if (_0 == null) { create(ref _0, 2045209720); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_BlueTeam [Type=via.gui.Panel]</summary>
		public class _PNL_BlueTeam_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_BlueTeam_() : base(){}
			public _PNL_BlueTeam_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Blue_HP_ PNL_BlueHP { get { if (_0 == null) { create(ref _0, 1864562120); } return _0; } }
			public _PNL_Blue_MP_ PNL_BlueMP { get { if (_1 == null) { create(ref _1, 288874646); } return _1; } }
			public _PNL_BlueIcon_ PNL_BlueIcon { get { if (_2 == null) { create(ref _2, 915810860); } return _2; } }
			public _PNL_BlueGauge_ PNL_BlueGauge { get { if (_3 == null) { create(ref _3, 1692518076); } return _3; } }
			public _PNL_BlueBg_ PNL_BlueBg { get { if (_4 == null) { create(ref _4, 2066093324); } return _4; } }
			public _PNL_BlueBeam_ PNL_BlueBeam { get { if (_5 == null) { create(ref _5, 296875570); } return _5; } }
			public _PNL_BlueLariat_ PNL_BlueLariat { get { if (_6 == null) { create(ref _6, 1154287894); } return _6; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_Blue_HP_ _0;
			private _PNL_Blue_MP_ _1;
			private _PNL_BlueIcon_ _2;
			private _PNL_BlueGauge_ _3;
			private _PNL_BlueBg_ _4;
			private _PNL_BlueBeam_ _5;
			private _PNL_BlueLariat_ _6;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Egi [Type=via.gui.Panel]</summary>
		public class _PNL_Egi_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Egi_() : base(){}
			public _PNL_Egi_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_MoveHP_Egi_ PNL_MoveHP_Egi { get { if (_0 == null) { create(ref _0, 4261571203); } return _0; } }
			public _PNL_MoveHP_BG_Egi_ PNL_MoveHP_BG_Egi { get { if (_1 == null) { create(ref _1, 12412087); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_MoveHP_Egi_ _0;
			private _PNL_MoveHP_BG_Egi_ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_InGame [Type=via.gui.Panel]</summary>
		public class _PNL_InGame_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_InGame_() : base(){}
			public _PNL_InGame_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_TimeLimit_ PNL_TimeLimit { get { if (_0 == null) { create(ref _0, 2584482054); } return _0; } }
			public _PNL_BlueTeam_ PNL_BlueTeam { get { if (_1 == null) { create(ref _1, 722750944); } return _1; } }
			public _PNL_PinkTeam_ PNL_PinkTeam { get { if (_2 == null) { create(ref _2, 2869258747); } return _2; } }
			public _PNL_MoveLife_ PNL_MoveLife { get { if (_3 == null) { create(ref _3, 822385170); } return _3; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_TimeLimit_ _0;
			private _PNL_BlueTeam_ _1;
			private _PNL_PinkTeam_ _2;
			private _PNL_MoveLife_ _3;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_MoveHP_Aari [Type=via.gui.Panel]</summary>
		public class _PNL_MoveHP_Aari_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_MoveHP_Aari_() : base(){}
			public _PNL_MoveHP_Aari_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP1 { get { if (_0 == null) { create(ref _0, 2426790930); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP2 { get { if (_1 == null) { create(ref _1, 3619105446); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP3 { get { if (_2 == null) { create(ref _2, 3556819081); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP4 { get { if (_3 == null) { create(ref _3, 1538221692); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP5 { get { if (_4 == null) { create(ref _4, 563650572); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_MoveLife5 { get { return _State_MoveLife5; } } 
			public string State_MoveLife4 { get { return _State_MoveLife4; } } 
			public string State_MoveLife3 { get { return _State_MoveLife3; } } 
			public string State_MoveLife2 { get { return _State_MoveLife2; } } 
			public string State_MoveLife1 { get { return _State_MoveLife1; } } 
			public string State_MoveLife0 { get { return _State_MoveLife0; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_MoveLife5 = "MoveLife5";
			private const string _State_MoveLife4 = "MoveLife4";
			private const string _State_MoveLife3 = "MoveLife3";
			private const string _State_MoveLife2 = "MoveLife2";
			private const string _State_MoveLife1 = "MoveLife1";
			private const string _State_MoveLife0 = "MoveLife0";
			#endregion
		}
		
		/// <summary>PNL_MoveHP_BG_Aari [Type=via.gui.Panel]</summary>
		public class _PNL_MoveHP_BG_Aari_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_MoveHP_BG_Aari_() : base(){}
			public _PNL_MoveHP_BG_Aari_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP1 { get { if (_0 == null) { create(ref _0, 2426790930); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP2 { get { if (_1 == null) { create(ref _1, 3619105446); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP3 { get { if (_2 == null) { create(ref _2, 3556819081); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP4 { get { if (_3 == null) { create(ref _3, 1538221692); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP5 { get { if (_4 == null) { create(ref _4, 563650572); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_MoveHP_BG_Egi [Type=via.gui.Panel]</summary>
		public class _PNL_MoveHP_BG_Egi_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_MoveHP_BG_Egi_() : base(){}
			public _PNL_MoveHP_BG_Egi_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP1 { get { if (_0 == null) { create(ref _0, 2368806892); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP2 { get { if (_1 == null) { create(ref _1, 4108067642); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP3 { get { if (_2 == null) { create(ref _2, 3803888176); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP4 { get { if (_3 == null) { create(ref _3, 3229955701); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP5 { get { if (_4 == null) { create(ref _4, 810787143); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_MoveHP_Egi [Type=via.gui.Panel]</summary>
		public class _PNL_MoveHP_Egi_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_MoveHP_Egi_() : base(){}
			public _PNL_MoveHP_Egi_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP1 { get { if (_0 == null) { create(ref _0, 2368806892); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP2 { get { if (_1 == null) { create(ref _1, 4108067642); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP3 { get { if (_2 == null) { create(ref _2, 3803888176); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP4 { get { if (_3 == null) { create(ref _3, 3229955701); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP5 { get { if (_4 == null) { create(ref _4, 810787143); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_MoveLife5 { get { return _State_MoveLife5; } } 
			public string State_MoveLife4 { get { return _State_MoveLife4; } } 
			public string State_MoveLife3 { get { return _State_MoveLife3; } } 
			public string State_MoveLife2 { get { return _State_MoveLife2; } } 
			public string State_MoveLife1 { get { return _State_MoveLife1; } } 
			public string State_MoveLife0 { get { return _State_MoveLife0; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_MoveLife5 = "MoveLife5";
			private const string _State_MoveLife4 = "MoveLife4";
			private const string _State_MoveLife3 = "MoveLife3";
			private const string _State_MoveLife2 = "MoveLife2";
			private const string _State_MoveLife1 = "MoveLife1";
			private const string _State_MoveLife0 = "MoveLife0";
			#endregion
		}
		
		/// <summary>PNL_MoveLife [Type=via.gui.Panel]</summary>
		public class _PNL_MoveLife_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_MoveLife_() : base(){}
			public _PNL_MoveLife_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Egi_ PNL_Egi { get { if (_0 == null) { create(ref _0, 3981423316); } return _0; } }
			public _PNL_Aari_ PNL_Aari { get { if (_1 == null) { create(ref _1, 1157208655); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_Egi_ _0;
			private _PNL_Aari_ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Num [Type=via.gui.Panel]</summary>
		public class _PNL_Num_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Num_() : base(){}
			public _PNL_Num_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_2st_ PNL_2st { get { if (_0 == null) { create(ref _0, 1779863038); } return _0; } }
			public _PNL_1st_ PNL_1st { get { if (_1 == null) { create(ref _1, 1543229812); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_2st_ _0;
			private _PNL_1st_ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_P_GaugeBg [Type=via.gui.Panel]</summary>
		public class _PNL_P_GaugeBg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_P_GaugeBg_() : base(){}
			public _PNL_P_GaugeBg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_P_bg { get { if (_0 == null) { create(ref _0, 2315622823); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_P_HPbg [Type=via.gui.Panel]</summary>
		public class _PNL_P_HPbg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_P_HPbg_() : base(){}
			public _PNL_P_HPbg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP1 { get { if (_0 == null) { create(ref _0, 2426790930); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP2 { get { if (_1 == null) { create(ref _1, 3619105446); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP3 { get { if (_2 == null) { create(ref _2, 3556819081); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP4 { get { if (_3 == null) { create(ref _3, 1538221692); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP5 { get { if (_4 == null) { create(ref _4, 563650572); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_P_MPbg [Type=via.gui.Panel]</summary>
		public class _PNL_P_MPbg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_P_MPbg_() : base(){}
			public _PNL_P_MPbg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP1 { get { if (_0 == null) { create(ref _0, 3402127364); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP2 { get { if (_1 == null) { create(ref _1, 2047470238); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP3 { get { if (_2 == null) { create(ref _2, 2284051575); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP4 { get { if (_3 == null) { create(ref _3, 2261239603); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP5 { get { if (_4 == null) { create(ref _4, 2317910823); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Pink_HP [Type=via.gui.Panel]</summary>
		public class _PNL_Pink_HP_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Pink_HP_() : base(){}
			public _PNL_Pink_HP_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP1 { get { if (_0 == null) { create(ref _0, 2426790930); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP2 { get { if (_1 == null) { create(ref _1, 3619105446); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP3 { get { if (_2 == null) { create(ref _2, 3556819081); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP4 { get { if (_3 == null) { create(ref _3, 1538221692); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP5 { get { if (_4 == null) { create(ref _4, 563650572); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Life5 { get { return _State_Life5; } } 
			public string State_Life4 { get { return _State_Life4; } } 
			public string State_Life3 { get { return _State_Life3; } } 
			public string State_Life2 { get { return _State_Life2; } } 
			public string State_Life1 { get { return _State_Life1; } } 
			public string State_Life0 { get { return _State_Life0; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_Life5 = "Life5";
			private const string _State_Life4 = "Life4";
			private const string _State_Life3 = "Life3";
			private const string _State_Life2 = "Life2";
			private const string _State_Life1 = "Life1";
			private const string _State_Life0 = "Life0";
			#endregion
		}
		
		/// <summary>PNL_Pink_MP [Type=via.gui.Panel]</summary>
		public class _PNL_Pink_MP_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Pink_MP_() : base(){}
			public _PNL_Pink_MP_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP1 { get { if (_0 == null) { create(ref _0, 3402127364); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP2 { get { if (_1 == null) { create(ref _1, 2047470238); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP3 { get { if (_2 == null) { create(ref _2, 2284051575); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP4 { get { if (_3 == null) { create(ref _3, 2261239603); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP5 { get { if (_4 == null) { create(ref _4, 2317910823); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_MP5 { get { return _State_MP5; } } 
			public string State_MP4 { get { return _State_MP4; } } 
			public string State_MP3 { get { return _State_MP3; } } 
			public string State_MP2 { get { return _State_MP2; } } 
			public string State_MP1 { get { return _State_MP1; } } 
			public string State_MP0 { get { return _State_MP0; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_MP5 = "MP5";
			private const string _State_MP4 = "MP4";
			private const string _State_MP3 = "MP3";
			private const string _State_MP2 = "MP2";
			private const string _State_MP1 = "MP1";
			private const string _State_MP0 = "MP0";
			#endregion
		}
		
		/// <summary>PNL_PinkBeam [Type=via.gui.Panel]</summary>
		public class _PNL_PinkBeam_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_PinkBeam_() : base(){}
			public _PNL_PinkBeam_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_BarPwitch { get { if (_0 == null) { create(ref _0, 3663482078); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_BarPwitch_bg { get { if (_1 == null) { create(ref _1, 1029591736); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_charge { get { return _State_charge; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_charge = "charge";
			#endregion
		}
		
		/// <summary>PNL_PinkBg [Type=via.gui.Panel]</summary>
		public class _PNL_PinkBg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_PinkBg_() : base(){}
			public _PNL_PinkBg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_P_HPbg_ PNL_P_HPbg { get { if (_0 == null) { create(ref _0, 4222990776); } return _0; } }
			public _PNL_P_MPbg_ PNL_P_MPbg { get { if (_1 == null) { create(ref _1, 2852244050); } return _1; } }
			public _PNL_P_GaugeBg_ PNL_P_GaugeBg { get { if (_2 == null) { create(ref _2, 4118883256); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_IconMPbg { get { if (_3 == null) { create(ref _3, 1226735192); } return _3; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_P_HPbg_ _0;
			private _PNL_P_MPbg_ _1;
			private _PNL_P_GaugeBg_ _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_PinkGauge [Type=via.gui.Panel]</summary>
		public class _PNL_PinkGauge_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_PinkGauge_() : base(){}
			public _PNL_PinkGauge_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_P { get { if (_0 == null) { create(ref _0, 3819571234); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_PinkIcon [Type=via.gui.Panel]</summary>
		public class _PNL_PinkIcon_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_PinkIcon_() : base(){}
			public _PNL_PinkIcon_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Icon_Aari { get { if (_0 == null) { create(ref _0, 3387308114); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_PinkLariat [Type=via.gui.Panel]</summary>
		public class _PNL_PinkLariat_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_PinkLariat_() : base(){}
			public _PNL_PinkLariat_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_lariat { get { if (_0 == null) { create(ref _0, 2045209720); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_PinkTeam [Type=via.gui.Panel]</summary>
		public class _PNL_PinkTeam_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_PinkTeam_() : base(){}
			public _PNL_PinkTeam_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Pink_HP_ PNL_PinkHP { get { if (_0 == null) { create(ref _0, 86198576); } return _0; } }
			public _PNL_Pink_MP_ PNL_PinkMP { get { if (_1 == null) { create(ref _1, 4179167749); } return _1; } }
			public _PNL_PinkIcon_ PNL_PinkIcon { get { if (_2 == null) { create(ref _2, 585173739); } return _2; } }
			public _PNL_PinkGauge_ PNL_PinkGauge { get { if (_3 == null) { create(ref _3, 4008563688); } return _3; } }
			public _PNL_PinkBg_ PNL_PinkBg { get { if (_4 == null) { create(ref _4, 802069434); } return _4; } }
			public _PNL_PinkBeam_ PNL_PinkBeam { get { if (_5 == null) { create(ref _5, 30715404); } return _5; } }
			public _PNL_PinkLariat_ PNL_PinkLariat { get { if (_6 == null) { create(ref _6, 782191651); } return _6; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_Pink_HP_ _0;
			private _PNL_Pink_MP_ _1;
			private _PNL_PinkIcon_ _2;
			private _PNL_PinkGauge_ _3;
			private _PNL_PinkBg_ _4;
			private _PNL_PinkBeam_ _5;
			private _PNL_PinkLariat_ _6;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Terop [Type=via.gui.Panel]</summary>
		public class _PNL_Terop_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Terop_() : base(){}
			public _PNL_Terop_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_FINISH { get { if (_0 == null) { create(ref _0, 4231464233); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_GO { get { if (_1 == null) { create(ref _1, 3180301116); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_READY { get { if (_2 == null) { create(ref _2, 2186148085); } return _2; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_Start { get { return _State_Start; } } 
			public string State_Finish { get { return _State_Finish; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_Start = "Start";
			private const string _State_Finish = "Finish";
			#endregion
		}
		
		/// <summary>PNL_TimeLimit [Type=via.gui.Panel]</summary>
		public class _PNL_TimeLimit_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_TimeLimit_() : base(){}
			public _PNL_TimeLimit_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Num_ PNL_Num { get { if (_0 == null) { create(ref _0, 493110921); } return _0; } }
			public _PNL__ PNL_Bg { get { if (_1 == null) { create(ref _1, 2350338275); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_Num_ _0;
			private _PNL__ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_UnderBg [Type=via.gui.Panel]</summary>
		public class _PNL_UnderBg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_UnderBg_() : base(){}
			public _PNL_UnderBg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_MIHON { get { if (_0 == null) { create(ref _0, 3150147910); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		#region Legacy GUI Parameter Variable IDs (GPI)
		
		// ※ 旧仕様向けの出力です。Rootや各コントロールのParamDefクラス以下に変数定義があるのでそちらを利用してください。
		
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Aari_Visibleに書き換えてください。")]
		public static string GPI_PNL_Aari_Visible = "PNL_Aari_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Egi_Visibleに書き換えてください。")]
		public static string GPI_PNL_Egi_Visible = "PNL_Egi_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_0_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_0_Visible = "tex_1st_0_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_1_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_1_Visible = "tex_1st_1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_2_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_2_Visible = "tex_1st_2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_3_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_3_Visible = "tex_1st_3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_4_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_4_Visible = "tex_1st_4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_5_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_5_Visible = "tex_1st_5_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_6_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_6_Visible = "tex_1st_6_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_7_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_7_Visible = "tex_1st_7_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_8_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_8_Visible = "tex_1st_8_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_9_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_9_Visible = "tex_1st_9_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_0_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_0_Visible = "tex_2st_0_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_1_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_1_Visible = "tex_2st_1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_2_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_2_Visible = "tex_2st_2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_3_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_3_Visible = "tex_2st_3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_4_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_4_Visible = "tex_2st_4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_5_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_5_Visible = "tex_2st_5_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_6_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_6_Visible = "tex_2st_6_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_7_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_7_Visible = "tex_2st_7_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_8_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_8_Visible = "tex_2st_8_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_9_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_9_Visible = "tex_2st_9_Visible";
		/// <summary>[Type Integer] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_B_RectWに書き換えてください。")]
		public static string GPI_tex_Bar_B_RectW = "tex_Bar_B_RectW";
		/// <summary>[Type Integer] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_P_RectWに書き換えてください。")]
		public static string GPI_tex_Bar_P_RectW = "tex_Bar_P_RectW";
		/// <summary>[Type Float2] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_B_Sizeに書き換えてください。")]
		public static string GPI_tex_Bar_B_Size = "tex_Bar_B_Size";
		/// <summary>[Type Float2] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_P_Sizeに書き換えてください。")]
		public static string GPI_tex_Bar_P_Size = "tex_Bar_P_Size";
		/// <summary>[Type Float3] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Aari_Positionに書き換えてください。")]
		public static string GPI_PNL_Aari_Position = "PNL_Aari_Position";
		/// <summary>[Type Float3] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Egi_Positionに書き換えてください。")]
		public static string GPI_PNL_Egi_Position = "PNL_Egi_Position";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Aari_HP_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Aari_HP_PlayState = "PNL_Aari_HP_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Egi_HP_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Egi_HP_PlayState = "PNL_Egi_HP_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Frula_Beam_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Frula_Beam_PlayState = "PNL_Frula_Beam_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Frula_MP_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Frula_MP_PlayState = "PNL_Frula_MP_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_MoveHP_Aari_PlayStateに書き換えてください。")]
		public static string GPI_PNL_MoveHP_Aari_PlayState = "PNL_MoveHP_Aari_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_MoveHP_Egi_PlayStateに書き換えてください。")]
		public static string GPI_PNL_MoveHP_Egi_PlayState = "PNL_MoveHP_Egi_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Seena_Beam_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Seena_Beam_PlayState = "PNL_Seena_Beam_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Sheena_MP_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Sheena_MP_PlayState = "PNL_Sheena_MP_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Terop_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Terop_PlayState = "PNL_Terop_PlayState";
		
		#endregion
		
	}
}

