//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはReEngineのGUIツールによって生成されました。
//     このファイルへの変更は、不正な動作の原因になったり、
//     コードが再生成されるときに損失したりしますので編集しないでください。
// </auto-generated>
//------------------------------------------------------------------------------

// [Settings]
// ExportUnusedSymbol = False
// ReferenceExternalSymbol = False
// UseGUIStringPath = False

namespace via.gui.asset
{
	public class InstructionsUI
	{
		// Root objects
		
		public static _Root_ Root { get { return new _Root_(1219645687); } }
		
		public static _PNL_Story_ PNL_Story { get { return new _PNL_Story_(3761913117); } }
		
		public static _PNL_Bg_ PNL_Bg { get { return new _PNL_Bg_(2350338275); } }
		
		// Symbol define
		public static class SymbolDef
		{
			/// <summary>[Type=via.gui.View]</summary>
			public static _Root_ Root { get { return new _Root_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Bg_ PNL_Bg { get { return new _PNL_Bg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Page1_ PNL_Page1 { get { return new _PNL_Page1_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Story_ PNL_Story { get { return new _PNL_Story_(); } }
		}
		
		// Symbols
		
		/// <summary>Root [Type=via.gui.View]</summary>
		public class _Root_ : via.gui.GUIHashPath<via.gui.View>
		{
			
			public _Root_() : base(){}
			public _Root_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Story_ PNL_Story { get { if (_0 == null) { create(ref _0, 3761913117); } return _0; } }
			public _PNL_Bg_ PNL_Bg { get { if (_1 == null) { create(ref _1, 2350338275); } return _1; } }
			
			public class _ParamVarDefine_
			{
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page2_Visible { get { return new GUIParamVarDefine<bool>(172571760); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page3_Visible { get { return new GUIParamVarDefine<bool>(3353903229); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page4_Visible { get { return new GUIParamVarDefine<bool>(1237043723); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page5_Visible { get { return new GUIParamVarDefine<bool>(3443149025); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page6_Visible { get { return new GUIParamVarDefine<bool>(2910024743); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page7_Visible { get { return new GUIParamVarDefine<bool>(4122048756); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page8_Visible { get { return new GUIParamVarDefine<bool>(1124603113); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page9_Visible { get { return new GUIParamVarDefine<bool>(1779934391); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page10_Visible { get { return new GUIParamVarDefine<bool>(2001141046); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page11_Visible { get { return new GUIParamVarDefine<bool>(1150010823); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page12_Visible { get { return new GUIParamVarDefine<bool>(388693496); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page13_Visible { get { return new GUIParamVarDefine<bool>(2844458171); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page14_Visible { get { return new GUIParamVarDefine<bool>(3751659094); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page15_Visible { get { return new GUIParamVarDefine<bool>(1726897021); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page16_Visible { get { return new GUIParamVarDefine<bool>(2618884713); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page17_Visible { get { return new GUIParamVarDefine<bool>(1997300101); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page18_Visible { get { return new GUIParamVarDefine<bool>(445808476); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page19_Visible { get { return new GUIParamVarDefine<bool>(735031013); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page20_Visible { get { return new GUIParamVarDefine<bool>(1495791594); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Page1_Visible { get { return new GUIParamVarDefine<bool>(1205358506); } }
			}
			public _ParamVarDefine_ ParamDef { get { if (_p == null) { _p = new _ParamVarDefine_(); } return _p; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>無効</summary>
			public string State_DISABLE { get { return _State_DISABLE; } } 
			/// <summary>IN演出</summary>
			public string State_FADE_IN { get { return _State_FADE_IN; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private _PNL_Story_ _0;
			private _PNL_Bg_ _1;
			private _ParamVarDefine_ _p;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_DISABLE = "DISABLE";
			private const string _State_FADE_IN = "FADE_IN";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_Bg [Type=via.gui.Panel]</summary>
		public class _PNL_Bg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Bg_() : base(){}
			public _PNL_Bg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bg { get { if (_0 == null) { create(ref _0, 3626212465); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Page1 [Type=via.gui.Panel]</summary>
		public class _PNL_Page1_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Page1_() : base(){}
			public _PNL_Page1_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Page { get { if (_0 == null) { create(ref _0, 3454668076); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Story [Type=via.gui.Panel]</summary>
		public class _PNL_Story_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Story_() : base(){}
			public _PNL_Story_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Page1_ PNL_Page20 { get { if (_0 == null) { create(ref _0, 3146464779); } return _0; } }
			public _PNL_Page1_ PNL_Page19 { get { if (_1 == null) { create(ref _1, 2536475156); } return _1; } }
			public _PNL_Page1_ PNL_Page18 { get { if (_2 == null) { create(ref _2, 837722460); } return _2; } }
			public _PNL_Page1_ PNL_Page17 { get { if (_3 == null) { create(ref _3, 126010499); } return _3; } }
			public _PNL_Page1_ PNL_Page16 { get { if (_4 == null) { create(ref _4, 1517837275); } return _4; } }
			public _PNL_Page1_ PNL_Page15 { get { if (_5 == null) { create(ref _5, 2894880885); } return _5; } }
			public _PNL_Page1_ PNL_Page14 { get { if (_6 == null) { create(ref _6, 386372183); } return _6; } }
			public _PNL_Page1_ PNL_Page13 { get { if (_7 == null) { create(ref _7, 3435768647); } return _7; } }
			public _PNL_Page1_ PNL_Page12 { get { if (_8 == null) { create(ref _8, 2928283295); } return _8; } }
			public _PNL_Page1_ PNL_Page11 { get { if (_9 == null) { create(ref _9, 2740834756); } return _9; } }
			public _PNL_Page1_ PNL_Page10 { get { if (_10 == null) { create(ref _10, 289390563); } return _10; } }
			public _PNL_Page1_ PNL_Page9 { get { if (_11 == null) { create(ref _11, 89405762); } return _11; } }
			public _PNL_Page1_ PNL_Page8 { get { if (_12 == null) { create(ref _12, 3776914954); } return _12; } }
			public _PNL_Page1_ PNL_Page7 { get { if (_13 == null) { create(ref _13, 876870028); } return _13; } }
			public _PNL_Page1_ PNL_Page6 { get { if (_14 == null) { create(ref _14, 1275394670); } return _14; } }
			public _PNL_Page1_ PNL_Page5 { get { if (_15 == null) { create(ref _15, 710597404); } return _15; } }
			public _PNL_Page1_ PNL_Page4 { get { if (_16 == null) { create(ref _16, 3700964660); } return _16; } }
			public _PNL_Page1_ PNL_Page3 { get { if (_17 == null) { create(ref _17, 2584577192); } return _17; } }
			public _PNL_Page1_ PNL_Page2 { get { if (_18 == null) { create(ref _18, 1388781100); } return _18; } }
			public _PNL_Page1_ PNL_Page1 { get { if (_19 == null) { create(ref _19, 3290564574); } return _19; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_Page1_ _0;
			private _PNL_Page1_ _1;
			private _PNL_Page1_ _2;
			private _PNL_Page1_ _3;
			private _PNL_Page1_ _4;
			private _PNL_Page1_ _5;
			private _PNL_Page1_ _6;
			private _PNL_Page1_ _7;
			private _PNL_Page1_ _8;
			private _PNL_Page1_ _9;
			private _PNL_Page1_ _10;
			private _PNL_Page1_ _11;
			private _PNL_Page1_ _12;
			private _PNL_Page1_ _13;
			private _PNL_Page1_ _14;
			private _PNL_Page1_ _15;
			private _PNL_Page1_ _16;
			private _PNL_Page1_ _17;
			private _PNL_Page1_ _18;
			private _PNL_Page1_ _19;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		#region Legacy GUI Parameter Variable IDs (GPI)
		
		// ※ 旧仕様向けの出力です。Rootや各コントロールのParamDefクラス以下に変数定義があるのでそちらを利用してください。
		
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page1_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page1_Visible = "PNL_Page1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page10_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page10_Visible = "PNL_Page10_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page11_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page11_Visible = "PNL_Page11_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page12_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page12_Visible = "PNL_Page12_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page13_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page13_Visible = "PNL_Page13_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page14_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page14_Visible = "PNL_Page14_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page15_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page15_Visible = "PNL_Page15_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page16_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page16_Visible = "PNL_Page16_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page17_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page17_Visible = "PNL_Page17_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page18_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page18_Visible = "PNL_Page18_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page19_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page19_Visible = "PNL_Page19_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page2_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page2_Visible = "PNL_Page2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page20_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page20_Visible = "PNL_Page20_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page3_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page3_Visible = "PNL_Page3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page4_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page4_Visible = "PNL_Page4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page5_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page5_Visible = "PNL_Page5_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page6_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page6_Visible = "PNL_Page6_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page7_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page7_Visible = "PNL_Page7_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page8_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page8_Visible = "PNL_Page8_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Page9_Visibleに書き換えてください。")]
		public static string GPI_PNL_Page9_Visible = "PNL_Page9_Visible";
		
		#endregion
		
	}
}

