//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはReEngineのGUIツールによって生成されました。
//     このファイルへの変更は、不正な動作の原因になったり、
//     コードが再生成されるときに損失したりしますので編集しないでください。
// </auto-generated>
//------------------------------------------------------------------------------

// [Settings]
// ExportUnusedSymbol = False
// ReferenceExternalSymbol = False
// UseGUIStringPath = False

namespace via.gui.asset
{
	public class test_InGameUI
	{
		// Root objects
		
		public static _Root_ Root { get { return new _Root_(1219645687); } }
		
		public static _PNL_Terop_ PNL_Terop { get { return new _PNL_Terop_(1534051143); } }
		
		public static _PNL_HP_ PNL_HP { get { return new _PNL_HP_(239697029); } }
		
		public static _PNL_Magic_ PNL_Magic { get { return new _PNL_Magic_(613996608); } }
		
		public static _PNL_Under_ PNL_Under { get { return new _PNL_Under_(1597967096); } }
		
		public static _PNL_TimeLimit_ PNL_TimeLimit { get { return new _PNL_TimeLimit_(2584482054); } }
		
		public static _PNL_UnderBg_ PNL_UnderBg { get { return new _PNL_UnderBg_(3467830877); } }
		
		// Symbol define
		public static class SymbolDef
		{
			/// <summary>[Type=via.gui.View]</summary>
			public static _Root_ Root { get { return new _Root_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL__ PNL_ { get { return new _PNL__(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_1st_ PNL_1st { get { return new _PNL_1st_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_2st_ PNL_2st { get { return new _PNL_2st_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_B_HPbg_ PNL_B_HPbg { get { return new _PNL_B_HPbg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_B_MPbg_ PNL_B_MPbg { get { return new _PNL_B_MPbg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Blue_HP_ PNL_Blue_HP { get { return new _PNL_Blue_HP_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Blue_Magic_ PNL_Blue_Magic { get { return new _PNL_Blue_Magic_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_HP_ PNL_HP { get { return new _PNL_HP_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Magic_ PNL_Magic { get { return new _PNL_Magic_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Num_ PNL_Num { get { return new _PNL_Num_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_P_HPbg_ PNL_P_HPbg { get { return new _PNL_P_HPbg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_P_MPbg_ PNL_P_MPbg { get { return new _PNL_P_MPbg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Pink_HP_ PNL_Pink_HP { get { return new _PNL_Pink_HP_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Pink_Magic_ PNL_Pink_Magic { get { return new _PNL_Pink_Magic_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Terop_ PNL_Terop { get { return new _PNL_Terop_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_TimeLimit_ PNL_TimeLimit { get { return new _PNL_TimeLimit_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Under_ PNL_Under { get { return new _PNL_Under_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_UnderBg_ PNL_UnderBg { get { return new _PNL_UnderBg_(); } }
		}
		
		// Symbols
		
		/// <summary>Root [Type=via.gui.View]</summary>
		public class _Root_ : via.gui.GUIHashPath<via.gui.View>
		{
			
			public _Root_() : base(){}
			public _Root_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Terop_ PNL_Terop { get { if (_0 == null) { create(ref _0, 1534051143); } return _0; } }
			public _PNL_HP_ PNL_HP { get { if (_1 == null) { create(ref _1, 239697029); } return _1; } }
			public _PNL_Magic_ PNL_Magic { get { if (_2 == null) { create(ref _2, 613996608); } return _2; } }
			public _PNL_Under_ PNL_Under { get { if (_3 == null) { create(ref _3, 1597967096); } return _3; } }
			public _PNL_TimeLimit_ PNL_TimeLimit { get { if (_4 == null) { create(ref _4, 2584482054); } return _4; } }
			public _PNL_UnderBg_ PNL_UnderBg { get { if (_5 == null) { create(ref _5, 3467830877); } return _5; } }
			
			public class _ParamVarDefine_
			{
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_MP1_Visible { get { return new GUIParamVarDefine<bool>(391786032); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_MP2_Visible { get { return new GUIParamVarDefine<bool>(1725349090); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_MP3_Visible { get { return new GUIParamVarDefine<bool>(1017953336); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_MP4_Visible { get { return new GUIParamVarDefine<bool>(2891133834); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_MP5_Visible { get { return new GUIParamVarDefine<bool>(3905258654); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_MP1_Visible { get { return new GUIParamVarDefine<bool>(399321750); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_MP2_Visible { get { return new GUIParamVarDefine<bool>(1937850635); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_MP3_Visible { get { return new GUIParamVarDefine<bool>(1840226254); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_MP4_Visible { get { return new GUIParamVarDefine<bool>(158275380); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_MP5_Visible { get { return new GUIParamVarDefine<bool>(207495689); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_HP1_Visible { get { return new GUIParamVarDefine<bool>(557792976); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_HP2_Visible { get { return new GUIParamVarDefine<bool>(2855174275); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_HP3_Visible { get { return new GUIParamVarDefine<bool>(1050136090); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_HP4_Visible { get { return new GUIParamVarDefine<bool>(22165122); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_B_HP5_Visible { get { return new GUIParamVarDefine<bool>(703351702); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_HP1_Visible { get { return new GUIParamVarDefine<bool>(3154388687); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_HP2_Visible { get { return new GUIParamVarDefine<bool>(1643277813); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_HP3_Visible { get { return new GUIParamVarDefine<bool>(111141385); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_HP4_Visible { get { return new GUIParamVarDefine<bool>(1847510418); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_P_HP5_Visible { get { return new GUIParamVarDefine<bool>(1828679209); } }
				
				/// <summary>[Type Float2] </summary>
				public GUIParamVarDefine<via.Float2> tex_Bar_B_Size { get { return new GUIParamVarDefine<via.Float2>(3939769030); } }
				
				/// <summary>[Type Integer] </summary>
				public GUIParamVarDefine<int> tex_Bar_B_RectW { get { return new GUIParamVarDefine<int>(568467340); } }
				
				/// <summary>[Type Float2] </summary>
				public GUIParamVarDefine<via.Float2> tex_Bar_P_Size { get { return new GUIParamVarDefine<via.Float2>(742372916); } }
				
				/// <summary>[Type Integer] </summary>
				public GUIParamVarDefine<int> tex_Bar_P_RectW { get { return new GUIParamVarDefine<int>(1746889748); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_Bar_Bwitch_Visible { get { return new GUIParamVarDefine<bool>(3499996645); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_BarPwitch_Visible { get { return new GUIParamVarDefine<bool>(3338931021); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_0_Visible { get { return new GUIParamVarDefine<bool>(158423174); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_1_Visible { get { return new GUIParamVarDefine<bool>(1350130747); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_2_Visible { get { return new GUIParamVarDefine<bool>(3139461295); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_3_Visible { get { return new GUIParamVarDefine<bool>(4133533458); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_4_Visible { get { return new GUIParamVarDefine<bool>(2399222301); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_5_Visible { get { return new GUIParamVarDefine<bool>(429601543); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_6_Visible { get { return new GUIParamVarDefine<bool>(598502784); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_7_Visible { get { return new GUIParamVarDefine<bool>(3125460697); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_8_Visible { get { return new GUIParamVarDefine<bool>(2349624524); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_2st_9_Visible { get { return new GUIParamVarDefine<bool>(251640015); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_0_Visible { get { return new GUIParamVarDefine<bool>(1853667042); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_1_Visible { get { return new GUIParamVarDefine<bool>(1959472007); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_2_Visible { get { return new GUIParamVarDefine<bool>(1355239676); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_3_Visible { get { return new GUIParamVarDefine<bool>(3289315109); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_4_Visible { get { return new GUIParamVarDefine<bool>(3174662094); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_5_Visible { get { return new GUIParamVarDefine<bool>(3778517565); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_6_Visible { get { return new GUIParamVarDefine<bool>(2439526607); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_7_Visible { get { return new GUIParamVarDefine<bool>(1643974157); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_8_Visible { get { return new GUIParamVarDefine<bool>(590842866); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> tex_1st_9_Visible { get { return new GUIParamVarDefine<bool>(2196750390); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Terop_PlayState { get { return new GUIParamVarDefine<string>(1299461484); } }
			}
			public _ParamVarDefine_ ParamDef { get { if (_p == null) { _p = new _ParamVarDefine_(); } return _p; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>無効</summary>
			public string State_DISABLE { get { return _State_DISABLE; } } 
			/// <summary>IN演出</summary>
			public string State_FADE_IN { get { return _State_FADE_IN; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private _PNL_Terop_ _0;
			private _PNL_HP_ _1;
			private _PNL_Magic_ _2;
			private _PNL_Under_ _3;
			private _PNL_TimeLimit_ _4;
			private _PNL_UnderBg_ _5;
			private _ParamVarDefine_ _p;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_DISABLE = "DISABLE";
			private const string _State_FADE_IN = "FADE_IN";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_ [Type=via.gui.Panel]</summary>
		public class _PNL__ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL__() : base(){}
			public _PNL__(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_limit { get { if (_0 == null) { create(ref _0, 1658911404); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_1st [Type=via.gui.Panel]</summary>
		public class _PNL_1st_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_1st_() : base(){}
			public _PNL_1st_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_0 { get { if (_0 == null) { create(ref _0, 1777110518); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_1 { get { if (_1 == null) { create(ref _1, 919952205); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_2 { get { if (_2 == null) { create(ref _2, 2799471434); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_3 { get { if (_3 == null) { create(ref _3, 2858414422); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_4 { get { if (_4 == null) { create(ref _4, 874142103); } return _4; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_5 { get { if (_5 == null) { create(ref _5, 2545007004); } return _5; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_6 { get { if (_6 == null) { create(ref _6, 1405700660); } return _6; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_7 { get { if (_7 == null) { create(ref _7, 3868133323); } return _7; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_8 { get { if (_8 == null) { create(ref _8, 1921129301); } return _8; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_9 { get { if (_9 == null) { create(ref _9, 286926054); } return _9; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private via.gui.GUIHashPath<via.gui.Texture> _5;
			private via.gui.GUIHashPath<via.gui.Texture> _6;
			private via.gui.GUIHashPath<via.gui.Texture> _7;
			private via.gui.GUIHashPath<via.gui.Texture> _8;
			private via.gui.GUIHashPath<via.gui.Texture> _9;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_2st [Type=via.gui.Panel]</summary>
		public class _PNL_2st_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_2st_() : base(){}
			public _PNL_2st_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_0 { get { if (_0 == null) { create(ref _0, 1777110518); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_1 { get { if (_1 == null) { create(ref _1, 919952205); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_2 { get { if (_2 == null) { create(ref _2, 2799471434); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_3 { get { if (_3 == null) { create(ref _3, 2858414422); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_4 { get { if (_4 == null) { create(ref _4, 874142103); } return _4; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_5 { get { if (_5 == null) { create(ref _5, 2545007004); } return _5; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_6 { get { if (_6 == null) { create(ref _6, 1405700660); } return _6; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_7 { get { if (_7 == null) { create(ref _7, 3868133323); } return _7; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_8 { get { if (_8 == null) { create(ref _8, 1921129301); } return _8; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_9 { get { if (_9 == null) { create(ref _9, 286926054); } return _9; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private via.gui.GUIHashPath<via.gui.Texture> _5;
			private via.gui.GUIHashPath<via.gui.Texture> _6;
			private via.gui.GUIHashPath<via.gui.Texture> _7;
			private via.gui.GUIHashPath<via.gui.Texture> _8;
			private via.gui.GUIHashPath<via.gui.Texture> _9;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_B_HPbg [Type=via.gui.Panel]</summary>
		public class _PNL_B_HPbg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_B_HPbg_() : base(){}
			public _PNL_B_HPbg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP1 { get { if (_0 == null) { create(ref _0, 2368806892); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP2 { get { if (_1 == null) { create(ref _1, 4108067642); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP3 { get { if (_2 == null) { create(ref _2, 3803888176); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP4 { get { if (_3 == null) { create(ref _3, 3229955701); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP5 { get { if (_4 == null) { create(ref _4, 810787143); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_B_MPbg [Type=via.gui.Panel]</summary>
		public class _PNL_B_MPbg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_B_MPbg_() : base(){}
			public _PNL_B_MPbg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP1 { get { if (_0 == null) { create(ref _0, 488565980); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP2 { get { if (_1 == null) { create(ref _1, 1667977655); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP3 { get { if (_2 == null) { create(ref _2, 2096175435); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP4 { get { if (_3 == null) { create(ref _3, 1763211850); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP5 { get { if (_4 == null) { create(ref _4, 962091416); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Blue_HP [Type=via.gui.Panel]</summary>
		public class _PNL_Blue_HP_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Blue_HP_() : base(){}
			public _PNL_Blue_HP_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP1 { get { if (_0 == null) { create(ref _0, 2368806892); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP2 { get { if (_1 == null) { create(ref _1, 4108067642); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP3 { get { if (_2 == null) { create(ref _2, 3803888176); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP4 { get { if (_3 == null) { create(ref _3, 3229955701); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_HP5 { get { if (_4 == null) { create(ref _4, 810787143); } return _4; } }
			public _PNL_B_HPbg_ PNL_B_HPbg { get { if (_5 == null) { create(ref _5, 2173925733); } return _5; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private _PNL_B_HPbg_ _5;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Blue_Magic [Type=via.gui.Panel]</summary>
		public class _PNL_Blue_Magic_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Blue_Magic_() : base(){}
			public _PNL_Blue_Magic_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP1 { get { if (_0 == null) { create(ref _0, 488565980); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP2 { get { if (_1 == null) { create(ref _1, 1667977655); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP3 { get { if (_2 == null) { create(ref _2, 2096175435); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP4 { get { if (_3 == null) { create(ref _3, 1763211850); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_B_MP5 { get { if (_4 == null) { create(ref _4, 962091416); } return _4; } }
			public _PNL_B_MPbg_ PNL_B_MPbg { get { if (_5 == null) { create(ref _5, 3840498066); } return _5; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private _PNL_B_MPbg_ _5;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_HP [Type=via.gui.Panel]</summary>
		public class _PNL_HP_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_HP_() : base(){}
			public _PNL_HP_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Blue_HP_ PNL_Blue_HP { get { if (_0 == null) { create(ref _0, 1316785971); } return _0; } }
			public _PNL_Pink_HP_ PNL_Pink_HP { get { if (_1 == null) { create(ref _1, 1471973243); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_Blue_HP_ _0;
			private _PNL_Pink_HP_ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Magic [Type=via.gui.Panel]</summary>
		public class _PNL_Magic_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Magic_() : base(){}
			public _PNL_Magic_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Blue_Magic_ PNL_Blue_Magic { get { if (_0 == null) { create(ref _0, 1877680031); } return _0; } }
			public _PNL_Pink_Magic_ PNL_Pink_Magic { get { if (_1 == null) { create(ref _1, 3915503981); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_Blue_Magic_ _0;
			private _PNL_Pink_Magic_ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Num [Type=via.gui.Panel]</summary>
		public class _PNL_Num_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Num_() : base(){}
			public _PNL_Num_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_2st_ PNL_2st { get { if (_0 == null) { create(ref _0, 1779863038); } return _0; } }
			public _PNL_1st_ PNL_1st { get { if (_1 == null) { create(ref _1, 1543229812); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_2st_ _0;
			private _PNL_1st_ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_P_HPbg [Type=via.gui.Panel]</summary>
		public class _PNL_P_HPbg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_P_HPbg_() : base(){}
			public _PNL_P_HPbg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP1 { get { if (_0 == null) { create(ref _0, 2426790930); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP2 { get { if (_1 == null) { create(ref _1, 3619105446); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP3 { get { if (_2 == null) { create(ref _2, 3556819081); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP4 { get { if (_3 == null) { create(ref _3, 1538221692); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP5 { get { if (_4 == null) { create(ref _4, 563650572); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_P_MPbg [Type=via.gui.Panel]</summary>
		public class _PNL_P_MPbg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_P_MPbg_() : base(){}
			public _PNL_P_MPbg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP1 { get { if (_0 == null) { create(ref _0, 3402127364); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP2 { get { if (_1 == null) { create(ref _1, 2047470238); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP3 { get { if (_2 == null) { create(ref _2, 2284051575); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP4 { get { if (_3 == null) { create(ref _3, 2261239603); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP5 { get { if (_4 == null) { create(ref _4, 2317910823); } return _4; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Pink_HP [Type=via.gui.Panel]</summary>
		public class _PNL_Pink_HP_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Pink_HP_() : base(){}
			public _PNL_Pink_HP_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP1 { get { if (_0 == null) { create(ref _0, 2426790930); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP2 { get { if (_1 == null) { create(ref _1, 3619105446); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP3 { get { if (_2 == null) { create(ref _2, 3556819081); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP4 { get { if (_3 == null) { create(ref _3, 1538221692); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_HP5 { get { if (_4 == null) { create(ref _4, 563650572); } return _4; } }
			public _PNL_P_HPbg_ PNL_P_HPbg { get { if (_5 == null) { create(ref _5, 4222990776); } return _5; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private _PNL_P_HPbg_ _5;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Pink_Magic [Type=via.gui.Panel]</summary>
		public class _PNL_Pink_Magic_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Pink_Magic_() : base(){}
			public _PNL_Pink_Magic_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP1 { get { if (_0 == null) { create(ref _0, 3402127364); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP2 { get { if (_1 == null) { create(ref _1, 2047470238); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP3 { get { if (_2 == null) { create(ref _2, 2284051575); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP4 { get { if (_3 == null) { create(ref _3, 2261239603); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P_MP5 { get { if (_4 == null) { create(ref _4, 2317910823); } return _4; } }
			public _PNL_P_MPbg_ PNL_P_MPbg { get { if (_5 == null) { create(ref _5, 2852244050); } return _5; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private _PNL_P_MPbg_ _5;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Terop [Type=via.gui.Panel]</summary>
		public class _PNL_Terop_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Terop_() : base(){}
			public _PNL_Terop_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_FINISH { get { if (_0 == null) { create(ref _0, 4231464233); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_GO { get { if (_1 == null) { create(ref _1, 3180301116); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_READY { get { if (_2 == null) { create(ref _2, 2186148085); } return _2; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_Start { get { return _State_Start; } } 
			public string State_Finish { get { return _State_Finish; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_Start = "Start";
			private const string _State_Finish = "Finish";
			#endregion
		}
		
		/// <summary>PNL_TimeLimit [Type=via.gui.Panel]</summary>
		public class _PNL_TimeLimit_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_TimeLimit_() : base(){}
			public _PNL_TimeLimit_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Num_ PNL_Num { get { if (_0 == null) { create(ref _0, 493110921); } return _0; } }
			public _PNL__ PNL_Bg { get { if (_1 == null) { create(ref _1, 2350338275); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private _PNL_Num_ _0;
			private _PNL__ _1;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Under [Type=via.gui.Panel]</summary>
		public class _PNL_Under_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Under_() : base(){}
			public _PNL_Under_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Icon_B { get { if (_0 == null) { create(ref _0, 3100322928); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Icon_B1 { get { if (_1 == null) { create(ref _1, 884969013); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Icon_P { get { if (_2 == null) { create(ref _2, 2739911206); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Icon_P1 { get { if (_3 == null) { create(ref _3, 2851968139); } return _3; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_Bwitch { get { if (_4 == null) { create(ref _4, 3269327807); } return _4; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_Bwitch_bg { get { if (_5 == null) { create(ref _5, 3371721027); } return _5; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_BarPwitch { get { if (_6 == null) { create(ref _6, 3663482078); } return _6; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_BarPwitch_bg { get { if (_7 == null) { create(ref _7, 1029591736); } return _7; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_B { get { if (_8 == null) { create(ref _8, 3105613049); } return _8; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_P { get { if (_9 == null) { create(ref _9, 3819571234); } return _9; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_B_bg { get { if (_10 == null) { create(ref _10, 1996911567); } return _10; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Bar_P_bg { get { if (_11 == null) { create(ref _11, 2315622823); } return _11; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private via.gui.GUIHashPath<via.gui.Texture> _4;
			private via.gui.GUIHashPath<via.gui.Texture> _5;
			private via.gui.GUIHashPath<via.gui.Texture> _6;
			private via.gui.GUIHashPath<via.gui.Texture> _7;
			private via.gui.GUIHashPath<via.gui.Texture> _8;
			private via.gui.GUIHashPath<via.gui.Texture> _9;
			private via.gui.GUIHashPath<via.gui.Texture> _10;
			private via.gui.GUIHashPath<via.gui.Texture> _11;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_UnderBg [Type=via.gui.Panel]</summary>
		public class _PNL_UnderBg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_UnderBg_() : base(){}
			public _PNL_UnderBg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_MIHON { get { if (_0 == null) { create(ref _0, 3150147910); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_H { get { if (_1 == null) { create(ref _1, 460511561); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_P { get { if (_2 == null) { create(ref _2, 3348546039); } return _2; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		#region Legacy GUI Parameter Variable IDs (GPI)
		
		// ※ 旧仕様向けの出力です。Rootや各コントロールのParamDefクラス以下に変数定義があるのでそちらを利用してください。
		
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_0_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_0_Visible = "tex_1st_0_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_1_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_1_Visible = "tex_1st_1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_2_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_2_Visible = "tex_1st_2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_3_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_3_Visible = "tex_1st_3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_4_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_4_Visible = "tex_1st_4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_5_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_5_Visible = "tex_1st_5_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_6_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_6_Visible = "tex_1st_6_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_7_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_7_Visible = "tex_1st_7_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_8_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_8_Visible = "tex_1st_8_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_1st_9_Visibleに書き換えてください。")]
		public static string GPI_tex_1st_9_Visible = "tex_1st_9_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_0_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_0_Visible = "tex_2st_0_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_1_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_1_Visible = "tex_2st_1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_2_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_2_Visible = "tex_2st_2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_3_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_3_Visible = "tex_2st_3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_4_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_4_Visible = "tex_2st_4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_5_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_5_Visible = "tex_2st_5_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_6_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_6_Visible = "tex_2st_6_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_7_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_7_Visible = "tex_2st_7_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_8_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_8_Visible = "tex_2st_8_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_2st_9_Visibleに書き換えてください。")]
		public static string GPI_tex_2st_9_Visible = "tex_2st_9_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_HP1_Visibleに書き換えてください。")]
		public static string GPI_tex_B_HP1_Visible = "tex_B_HP1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_HP2_Visibleに書き換えてください。")]
		public static string GPI_tex_B_HP2_Visible = "tex_B_HP2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_HP3_Visibleに書き換えてください。")]
		public static string GPI_tex_B_HP3_Visible = "tex_B_HP3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_HP4_Visibleに書き換えてください。")]
		public static string GPI_tex_B_HP4_Visible = "tex_B_HP4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_HP5_Visibleに書き換えてください。")]
		public static string GPI_tex_B_HP5_Visible = "tex_B_HP5_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_MP1_Visibleに書き換えてください。")]
		public static string GPI_tex_B_MP1_Visible = "tex_B_MP1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_MP2_Visibleに書き換えてください。")]
		public static string GPI_tex_B_MP2_Visible = "tex_B_MP2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_MP3_Visibleに書き換えてください。")]
		public static string GPI_tex_B_MP3_Visible = "tex_B_MP3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_MP4_Visibleに書き換えてください。")]
		public static string GPI_tex_B_MP4_Visible = "tex_B_MP4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_B_MP5_Visibleに書き換えてください。")]
		public static string GPI_tex_B_MP5_Visible = "tex_B_MP5_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_Bwitch_Visibleに書き換えてください。")]
		public static string GPI_tex_Bar_Bwitch_Visible = "tex_Bar_Bwitch_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_BarPwitch_Visibleに書き換えてください。")]
		public static string GPI_tex_BarPwitch_Visible = "tex_BarPwitch_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_HP1_Visibleに書き換えてください。")]
		public static string GPI_tex_P_HP1_Visible = "tex_P_HP1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_HP2_Visibleに書き換えてください。")]
		public static string GPI_tex_P_HP2_Visible = "tex_P_HP2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_HP3_Visibleに書き換えてください。")]
		public static string GPI_tex_P_HP3_Visible = "tex_P_HP3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_HP4_Visibleに書き換えてください。")]
		public static string GPI_tex_P_HP4_Visible = "tex_P_HP4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_HP5_Visibleに書き換えてください。")]
		public static string GPI_tex_P_HP5_Visible = "tex_P_HP5_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_MP1_Visibleに書き換えてください。")]
		public static string GPI_tex_P_MP1_Visible = "tex_P_MP1_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_MP2_Visibleに書き換えてください。")]
		public static string GPI_tex_P_MP2_Visible = "tex_P_MP2_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_MP3_Visibleに書き換えてください。")]
		public static string GPI_tex_P_MP3_Visible = "tex_P_MP3_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_MP4_Visibleに書き換えてください。")]
		public static string GPI_tex_P_MP4_Visible = "tex_P_MP4_Visible";
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.tex_P_MP5_Visibleに書き換えてください。")]
		public static string GPI_tex_P_MP5_Visible = "tex_P_MP5_Visible";
		/// <summary>[Type Integer] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_B_RectWに書き換えてください。")]
		public static string GPI_tex_Bar_B_RectW = "tex_Bar_B_RectW";
		/// <summary>[Type Integer] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_P_RectWに書き換えてください。")]
		public static string GPI_tex_Bar_P_RectW = "tex_Bar_P_RectW";
		/// <summary>[Type Float2] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_B_Sizeに書き換えてください。")]
		public static string GPI_tex_Bar_B_Size = "tex_Bar_B_Size";
		/// <summary>[Type Float2] </summary>
		[System.Obsolete("Root.ParamDef.tex_Bar_P_Sizeに書き換えてください。")]
		public static string GPI_tex_Bar_P_Size = "tex_Bar_P_Size";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Terop_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Terop_PlayState = "PNL_Terop_PlayState";
		
		#endregion
		
	}
}

