//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはReEngineのGUIツールによって生成されました。
//     このファイルへの変更は、不正な動作の原因になったり、
//     コードが再生成されるときに損失したりしますので編集しないでください。
// </auto-generated>
//------------------------------------------------------------------------------

// [Settings]
// ExportUnusedSymbol = False
// ReferenceExternalSymbol = False
// UseGUIStringPath = False

namespace via.gui.asset
{
	public class PauseGUI
	{
		// Root objects
		
		public static _Root_ Root { get { return new _Root_(1219645687); } }
		
		public static _PNL_Choice_ PNL_Choice { get { return new _PNL_Choice_(3222721482); } }
		
		public static _PNL_Press_ PNL_Press { get { return new _PNL_Press_(3361361189); } }
		
		public static _PNL_BG_ PNL_Bg { get { return new _PNL_BG_(2350338275); } }
		
		// Symbol define
		public static class SymbolDef
		{
			/// <summary>[Type=via.gui.View]</summary>
			public static _Root_ Root { get { return new _Root_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_BG_ PNL_BG { get { return new _PNL_BG_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Choice_ PNL_Choice { get { return new _PNL_Choice_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Press_ PNL_Press { get { return new _PNL_Press_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Quit_ PNL_Quit { get { return new _PNL_Quit_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_ReturnGame_ PNL_ReturnGame { get { return new _PNL_ReturnGame_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_ReturnTitle_ PNL_ReturnTitle { get { return new _PNL_ReturnTitle_(); } }
		}
		
		// Symbols
		
		/// <summary>Root [Type=via.gui.View]</summary>
		public class _Root_ : via.gui.GUIHashPath<via.gui.View>
		{
			
			public _Root_() : base(){}
			public _Root_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Choice_ PNL_Choice { get { if (_0 == null) { create(ref _0, 3222721482); } return _0; } }
			public _PNL_Press_ PNL_Press { get { if (_1 == null) { create(ref _1, 3361361189); } return _1; } }
			public _PNL_BG_ PNL_Bg { get { if (_2 == null) { create(ref _2, 2350338275); } return _2; } }
			
			public class _ParamVarDefine_
			{
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Choice_PlayState { get { return new GUIParamVarDefine<string>(3938334842); } }
			}
			public _ParamVarDefine_ ParamDef { get { if (_p == null) { _p = new _ParamVarDefine_(); } return _p; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>無効</summary>
			public string State_DISABLE { get { return _State_DISABLE; } } 
			/// <summary>IN演出</summary>
			public string State_FADE_IN { get { return _State_FADE_IN; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private _PNL_Choice_ _0;
			private _PNL_Press_ _1;
			private _PNL_BG_ _2;
			private _ParamVarDefine_ _p;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_DISABLE = "DISABLE";
			private const string _State_FADE_IN = "FADE_IN";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_BG [Type=via.gui.Panel]</summary>
		public class _PNL_BG_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_BG_() : base(){}
			public _PNL_BG_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Pause { get { if (_0 == null) { create(ref _0, 2715858345); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Choice [Type=via.gui.Panel]</summary>
		public class _PNL_Choice_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Choice_() : base(){}
			public _PNL_Choice_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_ReturnTitle_ PNL_ReturnTitle { get { if (_0 == null) { create(ref _0, 3557785270); } return _0; } }
			public _PNL_ReturnGame_ PNL_ReturnGame { get { if (_1 == null) { create(ref _1, 4265849180); } return _1; } }
			public _PNL_Quit_ PNL_Quit { get { if (_2 == null) { create(ref _2, 1623766563); } return _2; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_TitleSelect { get { return _State_TitleSelect; } } 
			public string State_ReturnSelect { get { return _State_ReturnSelect; } } 
			public string State_QuitSelect { get { return _State_QuitSelect; } } 
			
			#region field (internal)
			private _PNL_ReturnTitle_ _0;
			private _PNL_ReturnGame_ _1;
			private _PNL_Quit_ _2;
			private const uint _Pattern_Default = 0;
			private const string _State_TitleSelect = "TitleSelect";
			private const string _State_ReturnSelect = "ReturnSelect";
			private const string _State_QuitSelect = "QuitSelect";
			#endregion
		}
		
		/// <summary>PNL_Press [Type=via.gui.Panel]</summary>
		public class _PNL_Press_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Press_() : base(){}
			public _PNL_Press_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_PressA { get { if (_0 == null) { create(ref _0, 101829651); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Quit [Type=via.gui.Panel]</summary>
		public class _PNL_Quit_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Quit_() : base(){}
			public _PNL_Quit_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Back_n { get { if (_0 == null) { create(ref _0, 1606326478); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Back_y { get { if (_1 == null) { create(ref _1, 533543001); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Select { get { return _State_Select; } } 
			public string State_Unselect { get { return _State_Unselect; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_Select = "Select";
			private const string _State_Unselect = "Unselect";
			#endregion
		}
		
		/// <summary>PNL_ReturnGame [Type=via.gui.Panel]</summary>
		public class _PNL_ReturnGame_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_ReturnGame_() : base(){}
			public _PNL_ReturnGame_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Back_n { get { if (_0 == null) { create(ref _0, 1606326478); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Back_y { get { if (_1 == null) { create(ref _1, 533543001); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Select { get { return _State_Select; } } 
			public string State_Unselect { get { return _State_Unselect; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_Select = "Select";
			private const string _State_Unselect = "Unselect";
			#endregion
		}
		
		/// <summary>PNL_ReturnTitle [Type=via.gui.Panel]</summary>
		public class _PNL_ReturnTitle_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_ReturnTitle_() : base(){}
			public _PNL_ReturnTitle_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_GoTitle_n { get { if (_0 == null) { create(ref _0, 4035140198); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_GoTitle_y { get { if (_1 == null) { create(ref _1, 3847598146); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Select { get { return _State_Select; } } 
			public string State_Unselect { get { return _State_Unselect; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_Select = "Select";
			private const string _State_Unselect = "Unselect";
			#endregion
		}
		
		#region Legacy GUI Parameter Variable IDs (GPI)
		
		// ※ 旧仕様向けの出力です。Rootや各コントロールのParamDefクラス以下に変数定義があるのでそちらを利用してください。
		
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Choice_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Choice_PlayState = "PNL_Choice_PlayState";
		
		#endregion
		
	}
}

