//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはReEngineのGUIツールによって生成されました。
//     このファイルへの変更は、不正な動作の原因になったり、
//     コードが再生成されるときに損失したりしますので編集しないでください。
// </auto-generated>
//------------------------------------------------------------------------------

// [Settings]
// ExportUnusedSymbol = False
// ReferenceExternalSymbol = False
// UseGUIStringPath = False

namespace via.gui.asset
{
	public class ResultMovieGUI
	{
		// Root objects
		
		public static _Root_ Root { get { return new _Root_(1219645687); } }
		
		public static _PNL_popup_ PNL_Popup { get { return new _PNL_popup_(1704452925); } }
		
		public static _PNL_Movie_ PNL_Movie { get { return new _PNL_Movie_(2919268184); } }
		
		// Symbol define
		public static class SymbolDef
		{
			/// <summary>[Type=via.gui.View]</summary>
			public static _Root_ Root { get { return new _Root_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Draw_ PNL_Draw { get { return new _PNL_Draw_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_FluraWin_ PNL_FluraWin { get { return new _PNL_FluraWin_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Movie_ PNL_Movie { get { return new _PNL_Movie_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_popup_ PNL_popup { get { return new _PNL_popup_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_SheenaWin_ PNL_SheenaWin { get { return new _PNL_SheenaWin_(); } }
		}
		
		// Symbols
		
		/// <summary>Root [Type=via.gui.View]</summary>
		public class _Root_ : via.gui.GUIHashPath<via.gui.View>
		{
			
			public _Root_() : base(){}
			public _Root_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_popup_ PNL_Popup { get { if (_0 == null) { create(ref _0, 1704452925); } return _0; } }
			public _PNL_Movie_ PNL_Movie { get { if (_1 == null) { create(ref _1, 2919268184); } return _1; } }
			
			public class _ParamVarDefine_
			{
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Popup_PlayState { get { return new GUIParamVarDefine<string>(831492873); } }
			}
			public _ParamVarDefine_ ParamDef { get { if (_p == null) { _p = new _ParamVarDefine_(); } return _p; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>無効</summary>
			public string State_DISABLE { get { return _State_DISABLE; } } 
			/// <summary>IN演出</summary>
			public string State_FADE_IN { get { return _State_FADE_IN; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private _PNL_popup_ _0;
			private _PNL_Movie_ _1;
			private _ParamVarDefine_ _p;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_DISABLE = "DISABLE";
			private const string _State_FADE_IN = "FADE_IN";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_Draw [Type=via.gui.Panel]</summary>
		public class _PNL_Draw_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Draw_() : base(){}
			public _PNL_Draw_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_draw { get { if (_0 == null) { create(ref _0, 890459168); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_DROWon { get { return _State_DROWon; } } 
			public string State_DROWstart { get { return _State_DROWstart; } } 
			public string State_DROWoff { get { return _State_DROWoff; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DROWon = "DROWon";
			private const string _State_DROWstart = "DROWstart";
			private const string _State_DROWoff = "DROWoff";
			#endregion
		}
		
		/// <summary>PNL_FluraWin [Type=via.gui.Panel]</summary>
		public class _PNL_FluraWin_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_FluraWin_() : base(){}
			public _PNL_FluraWin_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_flura { get { if (_0 == null) { create(ref _0, 1321823065); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_WINon { get { return _State_WINon; } } 
			public string State_WINstart { get { return _State_WINstart; } } 
			public string State_WINoff { get { return _State_WINoff; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_WINon = "WINon";
			private const string _State_WINstart = "WINstart";
			private const string _State_WINoff = "WINoff";
			#endregion
		}
		
		/// <summary>PNL_Movie [Type=via.gui.Panel]</summary>
		public class _PNL_Movie_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Movie_() : base(){}
			public _PNL_Movie_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_movie { get { if (_0 == null) { create(ref _0, 2932673306); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_popup [Type=via.gui.Panel]</summary>
		public class _PNL_popup_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_popup_() : base(){}
			public _PNL_popup_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_SheenaWin_ PNL_SheenaWin { get { if (_0 == null) { create(ref _0, 3088965776); } return _0; } }
			public _PNL_FluraWin_ PNL_FluraWin { get { if (_1 == null) { create(ref _1, 628031601); } return _1; } }
			public _PNL_Draw_ PNL_Draw { get { if (_2 == null) { create(ref _2, 933561485); } return _2; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			public string State_SheenaWin { get { return _State_SheenaWin; } } 
			public string State_FluraWin { get { return _State_FluraWin; } } 
			public string State_DROW { get { return _State_DROW; } } 
			
			#region field (internal)
			private _PNL_SheenaWin_ _0;
			private _PNL_FluraWin_ _1;
			private _PNL_Draw_ _2;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_SheenaWin = "SheenaWin";
			private const string _State_FluraWin = "FluraWin";
			private const string _State_DROW = "DROW";
			#endregion
		}
		
		/// <summary>PNL_SheenaWin [Type=via.gui.Panel]</summary>
		public class _PNL_SheenaWin_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_SheenaWin_() : base(){}
			public _PNL_SheenaWin_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_sheena { get { if (_0 == null) { create(ref _0, 3027143281); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_WINon { get { return _State_WINon; } } 
			public string State_WINstart { get { return _State_WINstart; } } 
			public string State_WINoff { get { return _State_WINoff; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_WINon = "WINon";
			private const string _State_WINstart = "WINstart";
			private const string _State_WINoff = "WINoff";
			#endregion
		}
		
		#region Legacy GUI Parameter Variable IDs (GPI)
		
		// ※ 旧仕様向けの出力です。Rootや各コントロールのParamDefクラス以下に変数定義があるのでそちらを利用してください。
		
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Popup_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Popup_PlayState = "PNL_Popup_PlayState";
		
		#endregion
		
	}
}

