//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはReEngineのGUIツールによって生成されました。
//     このファイルへの変更は、不正な動作の原因になったり、
//     コードが再生成されるときに損失したりしますので編集しないでください。
// </auto-generated>
//------------------------------------------------------------------------------

// [Settings]
// ExportUnusedSymbol = False
// ReferenceExternalSymbol = False
// UseGUIStringPath = False

namespace via.gui.asset
{
	public class Title
	{
		// Root objects
		
		public static _Root_ Root { get { return new _Root_(1219645687); } }
		
		public static _PNL_Fade_ PNL_Fade { get { return new _PNL_Fade_(1502179475); } }
		
		public static _PNL_Credit_ PNL_Credit { get { return new _PNL_Credit_(1835002687); } }
		
		public static _PNL_Choice_ PNL_Choice { get { return new _PNL_Choice_(3222721482); } }
		
		public static _PNL_Press_ PNL_Press { get { return new _PNL_Press_(3361361189); } }
		
		public static _PNL_Bg_ PNL_Bg { get { return new _PNL_Bg_(2350338275); } }
		
		// Symbol define
		public static class SymbolDef
		{
			/// <summary>[Type=via.gui.View]</summary>
			public static _Root_ Root { get { return new _Root_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Begin_ PNL_Begin { get { return new _PNL_Begin_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Bg_ PNL_Bg { get { return new _PNL_Bg_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Choice_ PNL_Choice { get { return new _PNL_Choice_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Credit_ PNL_Credit { get { return new _PNL_Credit_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Fade_ PNL_Fade { get { return new _PNL_Fade_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_FastStart_ PNL_FastStart { get { return new _PNL_FastStart_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Press_ PNL_Press { get { return new _PNL_Press_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Quit_ PNL_Quit { get { return new _PNL_Quit_(); } }
		}
		
		// Symbols
		
		/// <summary>Root [Type=via.gui.View]</summary>
		public class _Root_ : via.gui.GUIHashPath<via.gui.View>
		{
			
			public _Root_() : base(){}
			public _Root_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Fade_ PNL_Fade { get { if (_0 == null) { create(ref _0, 1502179475); } return _0; } }
			public _PNL_Credit_ PNL_Credit { get { if (_1 == null) { create(ref _1, 1835002687); } return _1; } }
			public _PNL_Choice_ PNL_Choice { get { if (_2 == null) { create(ref _2, 3222721482); } return _2; } }
			public _PNL_Press_ PNL_Press { get { if (_3 == null) { create(ref _3, 3361361189); } return _3; } }
			public _PNL_Bg_ PNL_Bg { get { if (_4 == null) { create(ref _4, 2350338275); } return _4; } }
			
			public class _ParamVarDefine_
			{
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Choice_PlayState { get { return new GUIParamVarDefine<string>(3938334842); } }
				
				/// <summary>[Type State] </summary>
				public GUIParamVarDefine<string> PNL_Fade_PlayState { get { return new GUIParamVarDefine<string>(1559209121); } }
				
				/// <summary>[Type Bool] </summary>
				public GUIParamVarDefine<bool> PNL_Credit_Visible { get { return new GUIParamVarDefine<bool>(2766565130); } }
			}
			public _ParamVarDefine_ ParamDef { get { if (_p == null) { _p = new _ParamVarDefine_(); } return _p; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>無効</summary>
			public string State_DISABLE { get { return _State_DISABLE; } } 
			/// <summary>IN演出</summary>
			public string State_FADE_IN { get { return _State_FADE_IN; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private _PNL_Fade_ _0;
			private _PNL_Credit_ _1;
			private _PNL_Choice_ _2;
			private _PNL_Press_ _3;
			private _PNL_Bg_ _4;
			private _ParamVarDefine_ _p;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_DISABLE = "DISABLE";
			private const string _State_FADE_IN = "FADE_IN";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_Begin [Type=via.gui.Panel]</summary>
		public class _PNL_Begin_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Begin_() : base(){}
			public _PNL_Begin_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Start_n { get { if (_0 == null) { create(ref _0, 2764987195); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_Start_y { get { if (_1 == null) { create(ref _1, 2687071862); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Selected { get { return _State_Selected; } } 
			public string State_Unselected { get { return _State_Unselected; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_Selected = "Selected";
			private const string _State_Unselected = "Unselected";
			#endregion
		}
		
		/// <summary>PNL_Bg [Type=via.gui.Panel]</summary>
		public class _PNL_Bg_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Bg_() : base(){}
			public _PNL_Bg_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_TitleBg { get { if (_0 == null) { create(ref _0, 2794427066); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_creditbutton { get { if (_1 == null) { create(ref _1, 182264264); } return _1; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_title { get { if (_2 == null) { create(ref _2, 221701299); } return _2; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_sample { get { if (_3 == null) { create(ref _3, 1351355515); } return _3; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private via.gui.GUIHashPath<via.gui.Texture> _2;
			private via.gui.GUIHashPath<via.gui.Texture> _3;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Choice [Type=via.gui.Panel]</summary>
		public class _PNL_Choice_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Choice_() : base(){}
			public _PNL_Choice_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Begin_ PNL_Begin { get { if (_0 == null) { create(ref _0, 1211214490); } return _0; } }
			public _PNL_FastStart_ PNL_FastStart { get { if (_1 == null) { create(ref _1, 1197326639); } return _1; } }
			public _PNL_Quit_ PNL_Quit { get { if (_2 == null) { create(ref _2, 1623766563); } return _2; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Begin_select { get { return _State_Begin_select; } } 
			public string State_FastStart_select { get { return _State_FastStart_select; } } 
			public string State_Quit_select { get { return _State_Quit_select; } } 
			
			#region field (internal)
			private _PNL_Begin_ _0;
			private _PNL_FastStart_ _1;
			private _PNL_Quit_ _2;
			private const uint _Pattern_Default = 0;
			private const string _State_Begin_select = "Begin_select";
			private const string _State_FastStart_select = "FastStart_select";
			private const string _State_Quit_select = "Quit_select";
			#endregion
		}
		
		/// <summary>PNL_Credit [Type=via.gui.Panel]</summary>
		public class _PNL_Credit_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Credit_() : base(){}
			public _PNL_Credit_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_credit { get { if (_0 == null) { create(ref _0, 1976574738); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Fade [Type=via.gui.Panel]</summary>
		public class _PNL_Fade_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Fade_() : base(){}
			public _PNL_Fade_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Rect> rect_ { get { if (_0 == null) { create(ref _0, 4016130787); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Rect> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_FastStart [Type=via.gui.Panel]</summary>
		public class _PNL_FastStart_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_FastStart_() : base(){}
			public _PNL_FastStart_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_FastStart_n { get { if (_0 == null) { create(ref _0, 326169477); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_FastStart_y { get { if (_1 == null) { create(ref _1, 729676668); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Selected { get { return _State_Selected; } } 
			public string State_Unselected { get { return _State_Unselected; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_Selected = "Selected";
			private const string _State_Unselected = "Unselected";
			#endregion
		}
		
		/// <summary>PNL_Press [Type=via.gui.Panel]</summary>
		public class _PNL_Press_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Press_() : base(){}
			public _PNL_Press_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_Press { get { if (_0 == null) { create(ref _0, 4038382639); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		/// <summary>PNL_Quit [Type=via.gui.Panel]</summary>
		public class _PNL_Quit_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Quit_() : base(){}
			public _PNL_Quit_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_FastStart_n { get { if (_0 == null) { create(ref _0, 326169477); } return _0; } }
			public via.gui.GUIHashPath<via.gui.Texture> tex_FastStart_y { get { if (_1 == null) { create(ref _1, 729676668); } return _1; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			public string State_Selected { get { return _State_Selected; } } 
			public string State_Unselected { get { return _State_Unselected; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private via.gui.GUIHashPath<via.gui.Texture> _1;
			private const uint _Pattern_Default = 0;
			private const string _State_Selected = "Selected";
			private const string _State_Unselected = "Unselected";
			#endregion
		}
		
		#region Legacy GUI Parameter Variable IDs (GPI)
		
		// ※ 旧仕様向けの出力です。Rootや各コントロールのParamDefクラス以下に変数定義があるのでそちらを利用してください。
		
		/// <summary>[Type Bool] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Credit_Visibleに書き換えてください。")]
		public static string GPI_PNL_Credit_Visible = "PNL_Credit_Visible";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Choice_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Choice_PlayState = "PNL_Choice_PlayState";
		/// <summary>[Type State] </summary>
		[System.Obsolete("Root.ParamDef.PNL_Fade_PlayStateに書き換えてください。")]
		public static string GPI_PNL_Fade_PlayState = "PNL_Fade_PlayState";
		
		#endregion
		
	}
}

